name: Django CI & Postgres Test

on:
  workflow_call:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  django_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    env:
      SECRET_KEY: test_secret_key_we_will_make_a_better_one
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test